# Generated by Django 5.2.8 on 2025-12-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Nombre'),
        ),
    ]
