# Generated by Django 5.2.8 on 2025-12-13 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('username', models.CharField(max_length=100, verbose_name='Usuario SSH')),
                ('password', models.CharField(help_text='Se guardará en texto plano (Precaución)', max_length=255, verbose_name='Contraseña SSH')),
                ('initial_port', models.IntegerField(help_text='Inicio del rango de puertos', verbose_name='Puerto Inicial')),
                ('final_port', models.IntegerField(help_text='Fin del rango de puertos', verbose_name='Puerto Final')),
                ('ssh_port', models.IntegerField(default=22, verbose_name='Puerto de Conexión SSH')),
            ],
        ),
        migrations.CreateModel(
            name='PortServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField(verbose_name='Número de Puerto')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('assigned_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ports', to='core.client', verbose_name='Cliente Asignado')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='core.server')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.server', verbose_name='Servidor Asignado'),
        ),
    ]
